#!/bin/sh
function index {
    > index.txt
    for i in $@ ; do
        unzip -p $i .INFO >> index.txt
        echo "Path: $i" >> index.txt
    done
}

function indexal
{
> index.txt
find ./* -type f -name *bps |
	    while IFS= read file_name; do
	    
	    	tar -xf ${file_name}
	    		echo ${file_name:1}>>../> index.txt
		fi
	    done
}
